export const DocCompTitleOrder = {
  accordion: { title: 'Accordion', order: 1 },
  alerts: { title: 'Alerts', order: 2 },
  avatar: { title: 'Avatar', order: 3 },
  badge: { title: 'Badge', order: 4 },
  banner: { title: 'Banner', order: 5 },
  bottomNavigation: { title: 'Bottom Navigation', order: 6 },
  breadcrumb: { title: 'Breadcrumb', order: 7 },
  buttons: { title: 'Buttons', order: 8 },
  buttonGroup: { title: 'Button-group', order: 9 },
  card: { title: 'Card', order: 10 },
  carousel: { title: 'Carousel', order: 11 },
  chatBubble: { title: 'Chat Bubble', order: 12 },
  clipboard: { title: 'Clipboard', order: 13 },
  datepicker: { title: 'Datepicker', order: 14 },
  deviceMockups: { title: 'Device Mockups', order: 15 },
  drawer: { title: 'Drawer', order: 16 },
  dropdowns: { title: 'Dropdowns', order: 17 },
  footer: { title: 'Footer', order: 18 },
  forms: { title: 'Forms', order: 19 },
  gallery: { title: 'Gallery', order: 20 },
  Indicators: { title: 'Indicators', order: 21 },
  Jumbotron: { title: 'Jumbotron', order: 22 },
  kbd: { title: 'KBD', order: 23 },
  listGroup: { title: 'List Group', order: 24 },
  loading: { title: 'Loading', order: 25 },
  megaMenu: { title: 'Mega Menu', order: 26 },
  modal: { title: 'Modal', order: 27 },
  navbar: { title: 'Navbar', order: 28 },
  pagination: { title: 'Pagination', order: 29 },
  popover: { title: 'Popover', order: 30 },
  progress: { title: 'Progress', order: 31 },
  rating: { title: 'Rating', order: 32 },
  sidebar: { title: 'Sidebar', order: 33 },
  skeleton: { title: 'Skeleton', order: 34 },
  speedDial: { title: 'Speed Dial', order: 35 },
  spinner: { title: 'Spinner', order: 36 },
  stepper: { title: 'Stepper', order: 37 },
  tables: { title: 'Tables', order: 38 },
  tabs: { title: 'Tabs', order: 39 },
  tree: { title: 'Tree', order: 40 },
  timeline: { title: 'Timeline', order: 41 },
  toast: { title: 'Toast', order: 42 },
  tooltips: { title: 'Tooltips', order: 43 },
  typography: { title: 'Typography', order: 44 },
  video: { title: 'Video', order: 45 },
};
